version: "3.11"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=eanetdb
      - POSTGRES_USER=eanet
      - POSTGRES_PASSWORD=eanet123
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/.eanet/
    ports:
      - "8001:8001"
    depends_on:
      - db