# Generated by Django 4.2 on 2023-04-29 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="workStart",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 29, 17, 42, 36, 809089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
