# Generated by Django 4.2 on 2023-05-02 07:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0002_alter_employee_workstart"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWorkSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("editable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MPK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=6)),
                ("description", models.CharField(max_length=100)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_accept", "Do akceptacji"),
                            ("open", "Otwarty"),
                            ("to_colse", "Do zamknięcia"),
                            ("closed", "Zamknięty"),
                        ],
                        default="to_accept",
                        max_length=20,
                    ),
                ),
                ("declaredEndDate", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="workStart",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="MPKWorkSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employeeWorkHourSheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controlling.employeeworksheet",
                    ),
                ),
                (
                    "mpk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controlling.mpk",
                    ),
                ),
            ],
            options={
                "unique_together": {("employeeWorkHourSheet", "mpk")},
            },
        ),
        migrations.AddField(
            model_name="employeeworksheet",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="controlling.employee"
            ),
        ),
        migrations.CreateModel(
            name="HourOfWorkSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("numberOfHours", models.FloatField(blank=True, null=True)),
                (
                    "mpkWorkSheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controlling.mpkworksheet",
                    ),
                ),
            ],
            options={
                "unique_together": {("mpkWorkSheet", "day")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="employeeworksheet",
            unique_together={("employee", "month")},
        ),
    ]
